### ISSUE TITLE
Ignore some files

### ISSUE THREAD

**Issue by DanielAndreasen** [AtomLinter/linter-spell-latex#23]
Thanks for this fantastic package!
Is it possible to ignore spell check on some certain files. I don't want spell check on my `.bib` file since this is huge and has many strange names which are highlighted.
It could also be nice to remove spell check for `preamble.tex` if such a file is used, but this is not a main concern.

**Comment by yitzchak** [comment]
You can do this will `linter` directly. See AtomLinter/linter-spell#43

**Comment by DanielAndreasen** [comment]
Fantastic, thanks for the quick answer! :)
