### ISSUE TITLE
Commands are linted too

### ISSUE THREAD

**Issue by fkjogu** [AtomLinter/linter-spell-latex#26]
The linter first also marks basically half of the `\command`s. Only when I manually run the linter via `ctrl+shift+p` `Linter: lint` the linting is corrected. Can somebody confirm?

Using atom 1.19.6 on Debian Stretch

**Comment by Aerijo** [comment]
I can't repoduce this. Can you provide a screenshot, and a block of text (wrapped in ```) that shows the issue? Any steps to consistently reproduce would also be welcome.

The provided block should look like the following in the preview tab:
```
This is raw text
    See? All      spaces      are preserved
```

**Comment by Aerijo** [comment]
@fkjogu Does it go away after saving? I find it often checks everything when I first open a file, and only respects ignored scopes after the first save. I'm guessing this is the same issue, just that I'm indirectly invoking the linting.

**Comment by fkjogu** [comment]
I'm using `atom-ide` right now, which conflicts with `linter`. `linter-spell-latex` does not work at all with this setup. Maybe I should put this into another issue.

But this prevents me to reproduce it at the moment,

**Comment by fkjogu** [comment]
Cannot reproduce anymore. Must have been a nasty interaction with other packages. Closing this.
